/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csm;

import csm.util.Statistica;
import csm.util.FileHandler;
import csm.util.CSM_Constraints;
import java.io.File;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.Random;
import java.util.concurrent.Semaphore;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import sde.actor.ControlMachine;
import sde.actor.Simulation;
import sde.actor.distribuzioni.Distribuzione;
import sde.actor.distribuzioni.DistribuzioneErlang;
import sde.actor.distribuzioni.DistribuzioneEsponenziale;
import sde.actor.distribuzioni.DistribuzioneIperEsponenziale;
/**
 *
 * @author antonio
 */
public class CSM_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CSM_GUI
     */
    public CSM_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_pop = new javax.swing.JComboBox();
        combo_lam_router = new javax.swing.JComboBox();
        combo_lam_think = new javax.swing.JComboBox();
        combo_lam_st2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_n_erl = new javax.swing.JComboBox();
        combo_lam_erl = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        combo_lam_iper1 = new javax.swing.JComboBox();
        combo_lam_iper2 = new javax.swing.JComboBox();
        combo_pro_iper1 = new javax.swing.JComboBox();
        combo_prob_iper2 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        field_tEnd = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        field_risp_sist = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        field_risp_rout = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        field_risp_st2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        field_risp_erl = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        field_risp_iper = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        field_thr_sist = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        field_thr_rou = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        field_thr_st2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        field_thr_erl = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        field_thr_iper = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        field_uti_sist = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        field_uti_rou = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        field_uti_st2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        field_uti_erl = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        field_uti_iper = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        field_att_sist = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        field_att_rou = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        field_att_st2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        field_att_erl = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        field_att_iper = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        field_serv_sist = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        field_serv_rou = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        field_serv_st = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        field_serv_erl = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        field_serv_iper = new javax.swing.JTextField();
        start_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_item_save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Parametri Simulazione"), "Parametri"));

        jLabel1.setText("Popolazione");

        jLabel2.setText("λ-router");

        jLabel3.setText("λ-Think. Stat.");

        jLabel4.setText("λ-Stazione 2");

        combo_pop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "5", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        combo_lam_router.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2.3" }));

        combo_lam_think.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.01" }));

        combo_lam_st2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.8" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stazione 3-Earlang"));

        jLabel5.setText("n");

        jLabel6.setText("λ");

        combo_n_erl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16" }));

        combo_lam_erl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.6" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_n_erl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_lam_erl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combo_n_erl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_lam_erl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Stazione 4-Iper Exp."));

        jLabel7.setText("λ-Staz.1");

        jLabel8.setText("λ-Staz.2");

        jLabel9.setText("α-Staz.1");

        jLabel10.setText("α-Staz.2");

        combo_lam_iper1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5" }));

        combo_lam_iper2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5" }));

        combo_pro_iper1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.95" }));
        combo_pro_iper1.setToolTipText("");

        combo_prob_iper2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.05" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_pro_iper1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_lam_iper2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_lam_iper1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_prob_iper2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combo_lam_iper1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_lam_iper2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_pro_iper1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(combo_prob_iper2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel31.setText("Durata");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_pop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_lam_router, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_lam_think, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_lam_st2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_tEnd)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo_pop, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo_lam_router, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_lam_think, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_lam_st2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_tEnd)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Risultati Simulazione"));
        jTabbedPane1.setName(""); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

        jLabel12.setText("Sistema");
        jPanel4.add(jLabel12);

        field_risp_sist.setEditable(false);
        jPanel4.add(field_risp_sist);

        jLabel11.setText("Router");
        jPanel4.add(jLabel11);

        field_risp_rout.setEditable(false);
        jPanel4.add(field_risp_rout);

        jLabel13.setText("Stazione 2 (Exp.)");
        jPanel4.add(jLabel13);

        field_risp_st2.setEditable(false);
        jPanel4.add(field_risp_st2);

        jLabel14.setText("Stazione 3 (Erl.)");
        jPanel4.add(jLabel14);

        field_risp_erl.setEditable(false);
        jPanel4.add(field_risp_erl);

        jLabel15.setText("Stazione 4 (Iper)");
        jPanel4.add(jLabel15);

        field_risp_iper.setEditable(false);
        jPanel4.add(field_risp_iper);

        jTabbedPane1.addTab("Risposta", jPanel4);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

        jLabel16.setText("Sistema");
        jPanel8.add(jLabel16);

        field_thr_sist.setEditable(false);
        jPanel8.add(field_thr_sist);

        jLabel17.setText("Router");
        jPanel8.add(jLabel17);

        field_thr_rou.setEditable(false);
        jPanel8.add(field_thr_rou);

        jLabel18.setText("Stazione 2 (Exp.)");
        jPanel8.add(jLabel18);

        field_thr_st2.setEditable(false);
        jPanel8.add(field_thr_st2);

        jLabel19.setText("Stazione 3 (Erl.)");
        jPanel8.add(jLabel19);

        field_thr_erl.setEditable(false);
        jPanel8.add(field_thr_erl);

        jLabel20.setText("Stazione 4 (Iper)");
        jPanel8.add(jLabel20);

        field_thr_iper.setEditable(false);
        jPanel8.add(field_thr_iper);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Throughput", jPanel5);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

        jLabel26.setText("Sistema");
        jPanel10.add(jLabel26);

        field_uti_sist.setEditable(false);
        jPanel10.add(field_uti_sist);

        jLabel27.setText("Router");
        jPanel10.add(jLabel27);

        field_uti_rou.setEditable(false);
        jPanel10.add(field_uti_rou);

        jLabel28.setText("Stazione 2 (Exp.)");
        jPanel10.add(jLabel28);

        field_uti_st2.setEditable(false);
        jPanel10.add(field_uti_st2);

        jLabel29.setText("Stazione 3 (Erl.)");
        jPanel10.add(jLabel29);

        field_uti_erl.setEditable(false);
        jPanel10.add(field_uti_erl);

        jLabel30.setText("Stazione 4 (Iper)");
        jPanel10.add(jLabel30);

        field_uti_iper.setEditable(false);
        jPanel10.add(field_uti_iper);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Utilizzazione", jPanel6);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

        jLabel21.setText("Sistema");
        jPanel9.add(jLabel21);

        field_att_sist.setEditable(false);
        jPanel9.add(field_att_sist);

        jLabel22.setText("Router");
        jPanel9.add(jLabel22);

        field_att_rou.setEditable(false);
        jPanel9.add(field_att_rou);

        jLabel23.setText("Stazione 2 (Exp.)");
        jPanel9.add(jLabel23);

        field_att_st2.setEditable(false);
        jPanel9.add(field_att_st2);

        jLabel24.setText("Stazione 3 (Erl.)");
        jPanel9.add(jLabel24);

        field_att_erl.setEditable(false);
        jPanel9.add(field_att_erl);

        jLabel25.setText("Stazione 4 (Iper)");
        jPanel9.add(jLabel25);

        field_att_iper.setEditable(false);
        jPanel9.add(field_att_iper);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Attesa", jPanel7);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

        jLabel32.setText("Sistema");
        jPanel12.add(jLabel32);

        field_serv_sist.setEditable(false);
        jPanel12.add(field_serv_sist);

        jLabel33.setText("Router");
        jPanel12.add(jLabel33);

        field_serv_rou.setEditable(false);
        jPanel12.add(field_serv_rou);

        jLabel34.setText("Stazione 2 (Exp.)");
        jPanel12.add(jLabel34);

        field_serv_st.setEditable(false);
        jPanel12.add(field_serv_st);

        jLabel35.setText("Stazione 3 (Erl.)");
        jPanel12.add(jLabel35);

        field_serv_erl.setEditable(false);
        jPanel12.add(field_serv_erl);

        jLabel36.setText("Stazione 4 (Iper)");
        jPanel12.add(jLabel36);

        field_serv_iper.setEditable(false);
        jPanel12.add(field_serv_iper);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Servizio", jPanel11);

        start_button.setText("Start");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        menu_item_save.setText("Salva");
        menu_item_save.setEnabled(false);
        menu_item_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_saveActionPerformed(evt);
            }
        });
        jMenu1.add(menu_item_save);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
       try{
            Semaphore s = new Semaphore(0);
            Bootstrap engine = new Bootstrap(s);
            Observer updater = new Updater();
            engine.addObserver(updater);
            new Thread(engine).start();
            start_button.enableInputMethods(false);
            s.acquire();
            if( !engine.getErrore()){ JOptionPane.showMessageDialog(rootPane, "Simulazione Terminata");menu_item_save.setEnabled(true);}
            else{ JOptionPane.showMessageDialog(rootPane, "Errore durante la simulazione");}
        }catch(Exception e){}
    }//GEN-LAST:event_start_buttonActionPerformed

    private void menu_item_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_saveActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showSaveDialog(this);
        File f = chooser.getSelectedFile();
        if( f != null ){
            FileHandler handler = new FileHandler();
            handler.setResult(s);
            try {
                if( f.exists() ){
                    int scelta = JOptionPane.showConfirmDialog(rootPane,"Sovrascrivere file");
                    if( scelta == 0 ){
                        handler.setOutput(f);handler.sovrascriviFile();
                    }
                }else{
                    f.createNewFile();handler.setOutput(f);handler.creaFile();
                }
            } catch (IOException ex) {JOptionPane.showMessageDialog(this, "Errore!");}
        }
    }//GEN-LAST:event_menu_item_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSM_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_lam_erl;
    private javax.swing.JComboBox combo_lam_iper1;
    private javax.swing.JComboBox combo_lam_iper2;
    private javax.swing.JComboBox combo_lam_router;
    private javax.swing.JComboBox combo_lam_st2;
    private javax.swing.JComboBox combo_lam_think;
    private javax.swing.JComboBox combo_n_erl;
    private javax.swing.JComboBox combo_pop;
    private javax.swing.JComboBox combo_pro_iper1;
    private javax.swing.JComboBox combo_prob_iper2;
    private javax.swing.JTextField field_att_erl;
    private javax.swing.JTextField field_att_iper;
    private javax.swing.JTextField field_att_rou;
    private javax.swing.JTextField field_att_sist;
    private javax.swing.JTextField field_att_st2;
    private javax.swing.JTextField field_risp_erl;
    private javax.swing.JTextField field_risp_iper;
    private javax.swing.JTextField field_risp_rout;
    private javax.swing.JTextField field_risp_sist;
    private javax.swing.JTextField field_risp_st2;
    private javax.swing.JTextField field_serv_erl;
    private javax.swing.JTextField field_serv_iper;
    private javax.swing.JTextField field_serv_rou;
    private javax.swing.JTextField field_serv_sist;
    private javax.swing.JTextField field_serv_st;
    private javax.swing.JTextField field_tEnd;
    private javax.swing.JTextField field_thr_erl;
    private javax.swing.JTextField field_thr_iper;
    private javax.swing.JTextField field_thr_rou;
    private javax.swing.JTextField field_thr_sist;
    private javax.swing.JTextField field_thr_st2;
    private javax.swing.JTextField field_uti_erl;
    private javax.swing.JTextField field_uti_iper;
    private javax.swing.JTextField field_uti_rou;
    private javax.swing.JTextField field_uti_sist;
    private javax.swing.JTextField field_uti_st2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menu_item_save;
    private javax.swing.JButton start_button;
    // End of variables declaration//GEN-END:variables
    private final Statistica s = new Statistica();
    


private class Bootstrap extends Observable implements Runnable { 
    
    private final Semaphore sem;
    private boolean errore = false;

    public Bootstrap(Semaphore sem) {
        this.sem = sem;
    }
    
    
    private String getParameter(JComponent c){
        if( c instanceof JComboBox ){ return (String) ((JComboBox)c).getSelectedItem(); }
        if( c instanceof JTextField ){ return ((JTextField)c).getText();}
        return null;
    }


    @Override
    public void run() {
         try {
            double[] iper_lam = {
                Double.valueOf(getParameter(combo_lam_iper1)),
                Double.valueOf(getParameter(combo_lam_iper2))
            };
        
            double[] iper_prob = {
                Double.valueOf(getParameter(combo_pro_iper1)),
                Double.valueOf(getParameter(combo_prob_iper2))
            };
        
            int tEnd = Integer.valueOf(getParameter(field_tEnd));
        
            Random r = new Random();
            Distribuzione d0 = new DistribuzioneEsponenziale(Double.valueOf(getParameter(combo_lam_think)),r);
            Distribuzione d1 = new DistribuzioneEsponenziale(Double.valueOf(getParameter(combo_lam_router)), r);
            Distribuzione d2 = new DistribuzioneEsponenziale(Double.valueOf(getParameter(combo_lam_st2)), r);
            Distribuzione d3 = new DistribuzioneErlang(Integer.valueOf(getParameter(combo_n_erl)),
                                                        Double.valueOf(getParameter(combo_lam_erl)), r);
	
            Distribuzione d4 = new DistribuzioneIperEsponenziale(iper_prob,iper_lam,r);
            ControlMachine cm = new Simulation(tEnd);
            //Stazioni 
            StazioneIF s_riflessione = new StazioneRiflessione();
            StazioneIF router = new Router();
            StazioneIF s2 = new StazioneReale();
            StazioneIF s3 = new StazioneReale();
            StazioneIF s4 = new StazioneReale();
            StazioneIF[] stazioni = { s_riflessione,s2 , s3 ,s4 };

            //bootstrap sazioni
            s_riflessione.send(new StazioneRiflessioneIF.Init(router, d0, Integer.parseInt(getParameter(combo_pop))));
            router.send(new RouterIF.Init(stazioni, CSM_Constraints.PROB_INSTRADAMENTI, d1));
            s2.send(new StazioneRealeIF.Init(router, d2));
            s3.send(new StazioneRealeIF.Init(router, d3));
            s4.send(new StazioneRealeIF.Init(router, d4));
            cm.controller();
            
            s.rate_router = Double.valueOf(getParameter(combo_lam_router));
            s.n_popolazione = Integer.valueOf(getParameter(combo_pop));
            s.risposta_sistema = s_riflessione.getOsservatore().getMediaTempoRisposta();
            s.risposta_router = router.getOsservatore().getMediaTempoRisposta();
            s.risposta_stazione2 = s2.getOsservatore().getMediaTempoRisposta();
            s.risposta_stazione3 = s3.getOsservatore().getMediaTempoRisposta();
            s.risposta_stazione4 = s4.getOsservatore().getMediaTempoRisposta();
            s.throughput_sistema = s_riflessione.getOsservatore().getThroughput(tEnd);
            s.throughput_router = router.getOsservatore().getThroughput(tEnd);
            s.throughput_stazione2 = s2.getOsservatore().getThroughput(tEnd);
            s.throughput_stazone3 = s3.getOsservatore().getThroughput(tEnd);
            s.throughput_stazione4 = s4.getOsservatore().getThroughput(tEnd);
            s.utilizzazione_sistema = s_riflessione.getOsservatore().getUtilizzazione(tEnd);
            s.utilizzazione_router = router.getOsservatore().getUtilizzazione(tEnd);
            s.utilizzazione_stazione2 = s2.getOsservatore().getUtilizzazione(tEnd);
            s.utilizzazione_stazone3 = s3.getOsservatore().getUtilizzazione(tEnd);
            s.utilizzazione_stazione4 = s4.getOsservatore().getUtilizzazione(tEnd);
            s.attesa_router = router.getOsservatore().getMediaTempoCoda();
            s.attesa_stazione2 = s2.getOsservatore().getMediaTempoCoda();
            s.attesa_stazione3 = s3.getOsservatore().getMediaTempoCoda();
            s.attesa_stazione4 = s4.getOsservatore().getMediaTempoCoda();
            s.servizio_router = router.getOsservatore().getMediaTempoServizio();
            s.servizio_stazione2 = s2.getOsservatore().getMediaTempoServizio();
            s.servizio_stazione3 = s3.getOsservatore().getMediaTempoServizio();
            s.servizio_stazione4 = s4.getOsservatore().getMediaTempoServizio();
            
            setChanged();
            notifyObservers(s);
            sem.release();
            } catch (Exception ex) {
                errore = true;
                sem.release();
                JOptionPane.showMessageDialog(rootPane, "Errore durante la simulazione,rivedere parametri");
            }
    }
   
    public boolean getErrore(){ return errore;}

}//Bootstrap

    
private class Updater implements Observer{ 

        @Override
        public void update(Observable o, Object arg) {
            Statistica s = (Statistica) arg;
            field_att_erl.setText(String.valueOf(s.attesa_stazione3));
            field_att_iper.setText(String.valueOf(s.attesa_stazione4));
            field_att_rou.setText(String.valueOf(s.attesa_router));
            field_att_sist.setText("Nan");
            field_att_st2.setText(String.valueOf(s.attesa_stazione2));
            field_risp_erl.setText(String.valueOf(s.risposta_stazione3));
            field_risp_iper.setText(String.valueOf(s.risposta_stazione4));
            field_risp_rout.setText(String.valueOf(s.risposta_router));
            field_risp_sist.setText(String.valueOf(s.risposta_sistema));
            field_risp_st2.setText(String.valueOf(s.risposta_stazione2));
            field_thr_erl.setText(String.valueOf(s.throughput_stazone3));
            field_thr_iper.setText(String.valueOf(s.throughput_stazione4));
            field_thr_rou.setText(String.valueOf(s.throughput_router));
            field_thr_sist.setText(String.valueOf(s.throughput_sistema));
            field_thr_st2.setText(String.valueOf(s.throughput_stazione2));
            field_uti_erl.setText(String.valueOf(s.utilizzazione_stazone3));
            field_uti_iper.setText(String.valueOf(s.utilizzazione_stazione4));
            field_uti_rou.setText(String.valueOf(s.utilizzazione_router));
            field_uti_sist.setText(String.valueOf(s.utilizzazione_sistema));
            field_uti_st2.setText(String.valueOf(s.utilizzazione_stazione2));
            field_serv_erl.setText(String.valueOf(s.servizio_stazione3));
            field_serv_iper.setText(String.valueOf(s.servizio_stazione4));
            field_serv_rou.setText(String.valueOf(s.servizio_router));
            field_serv_sist.setText("Nan");
            field_serv_st.setText(String.valueOf(s.servizio_stazione2));
        }   
    
    }



}
